databases:
  - name: dewey2_db
    databaseName: dewey2_production
    user: dewey2
    plan: free

services:
  - type: web
    name: dewey2
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dewey2_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: dewey2-redis
          property: connectionString

  - type: worker
    name: dewey2-worker
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -C config/sidekiq.yml
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dewey2_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: dewey2-redis
          property: connectionString

  - type: redis
    name: dewey2-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction