:verbose: false
:concurrency: <%= ENV.fetch("RAILS_MAX_THREADS", 10).to_i %>
:timeout: 30

:queues:
  - [urgent, 3]
  - [default, 2]
  - [low_priority, 1]
  - mailers

development:
  :concurrency: 5

production:
  :concurrency: <%= ENV.fetch("RAILS_MAX_THREADS", 10).to_i %>