reddit:
  - RoastMyStartup
  - AlphaandBetausers
  - GrowthHacking
  - Digitalnomad
  - Promotereddit
  - Entrepreneur
  - EntrepreneurRideAlong
  - IMadeThis
  - IndieBiz
  - SideProject
  - SmallBusiness
  - Startups
  - Growmybusiness
  - Linkbuilding
  - SEO
  - Freepromote
  - SocialMediaMarketing
  - Analytics
  - Content_marketing
  - Advertising
  - PPC
  - AskMarketing

# discord:
#   - Hack2skill
#   - GCES
#   - Tech Startup Community
#   - Everything Startup
#   - Startup Growth Hub
#   - Furlough
#   - Startups and Entrepreneurship
#   - Starthub
#   - Art Code
#   - Million Dollar Weekend

# slack:
#   - OnlineGeniuses
#   - Marketers
#   - audienti
#   - crohacks
#   - productled
#   - revgenius
#   - demandcurve
#   - superpath
#   - email
#   - peakfreelance